### ISSUE TITLE
fb not reading all info

### ISSUE THREAD

**Issue by sasikanth513** [meteorclub/shareit#28]
This is my url
http://www.meteorsnippets.com/blog/upload-files-to-cloud-services

I'm using meteor blog with existig shareit package in my url I've image and all the desc.

I can see meta tags in the code
![fbog](https://cloud.githubusercontent.com/assets/6153816/5617721/bbd40238-9537-11e4-9ed1-9dff977a1007.png)

but when I share them in fb, images are not showing in the sharing page.

I tried to debug using fb debug tool , I fetched new scraping info,it is throwing some errors like

![fbscrap](https://cloud.githubusercontent.com/assets/6153816/5617735/d933eae6-9537-11e4-96a3-e0300f74ab10.png)

This is what fb is reading from that url
![fbreading](https://cloud.githubusercontent.com/assets/6153816/5617743/e437dde4-9537-11e4-9d97-0df0715c0eba.png)

I deployed my site in meteor servers, Is that the issue?

**Comment by rashmimhatre100** [comment]
Hello Mate,Is your shareData reflecting on your post? If yes can you please share solution.
